# https://taskfile.dev
version: '3'
vars:
  BINFILE: gtmpl

tasks:
  default:
    cmds:
      - go get
      - CGO_ENABLED=0 go build .
      - upx ./{{.BINFILE}}
    # silent: true
    dir: src
    sources:
      - main.go
      - go*
      - gitlab*/*go
    method: checksum
    generates:
      - "{{.BINFILE}}"

  
  snapshot:
    cmds:
      - GITLAB_TOKEN="" goreleaser --rm-dist --snapshot
    
  release:
    cmds:
      - GITLAB_TOKEN="" goreleaser --rm-dist